### ISSUE TITLE
About ResourceLoader#getResource() and Scene#getStyleSheets()#add()

### ISSUE THREAD

**Issue by Xelopie** [CastleLab/COMP3021-2020Fall-PA2-Student-Version#12]
This question might be a bit off topic but I am just somehow curious.

In my trial for the program, I found that only **absolute path** which we get from the ResourceLoader#getResource() **works** for Scene.getStyleSheets().add(). I tried some other path like "src/main/resources/styles/styles.css" or "file:/src/main/resources/styles/styles.css" to get the style sheet in getStyleSheets().add() but all failed (cannot find such stylesheet). 

I tried to look for some "relative path solution" for getStyleSheets().add() in Google but the answer is still confusing me. Is it a must to use absolute path in this method? Or is there a "relative path solution" to get style sheets?

**Comment by zcmiyano** [comment]
I'm also quite confused here. May I ask what does RES_PATH mean? Also what does "Absolute path to the resource file" mean? Is it from the root of this project directory or root of my computer? I can get the absolute path from the root of my computer, but it's pretty weird that only the absolute path of ResourceLoader way doesn't work for me, while many other ways work.

**Comment by ArabelaTso** [comment]
To answer Xelopie's question:

> In my trial for the program, I found that only absolute path which we get from the ResourceLoader#getResource() works for Scene.getStyleSheets().add(). I tried some other path like "src/main/resources/styles/styles.css" or "file:/src/main/resources/styles/styles.css" to get the style sheet in getStyleSheets().add() but all failed (cannot find such stylesheet).
> I tried to look for some "relative path solution" for getStyleSheets().add() in Google but the answer is still confusing me. Is it a must to use absolute path in this method? Or is there a "relative path solution" to get style sheets?

As you tried, when new an image or load style css, the absolute path is needed. While in getResource(), you can use relative path. The solution works as follow:
1. Assign RES_PATH as an absolute path to `src/main/resources`
2. In getResource(), pass in a relative path, and use `resolve` method in java.nio.file.Path, like `RES_PATH.resolve(relative_path)`, where the relative path starts from `resource` (i.e., `style/style.css`).

To answer zcmiyano's question:

> May I ask what does RES_PATH mean? 

RES_PATH means the absolute path to `src/main/resources`. An easy way to get the absolute path is to utilize `java.nio.file.Path#toAbsolutePath()`.  

> Also what does "Absolute path to the resource file" mean?

(Copy from Google) An absolute path refers to the complete details needed to locate a file or folder, starting from the root element and ending with the other subdirectories. 

For example, in Windows, you should see something like: `C:\home\username\...`, in Mac, something like `/Users/username` and `/home/username/...`.

> I can get the absolute path from the root of my computer, but it's pretty weird that only the absolute path of ResourceLoader way doesn't work for me, while many other ways work.

Since there are many other ways work for you, then it is ok to use either of them. 

### [IMPORTANT] To other students who have problems in reading resource files
Just in case some other students have the similar problem, here are some hints:
- Once the absolute path has been acquired, when converting to string, you also need two methods before `toString()`: `java.io.File#toFile()` and `java.io.File#toURI()`. Especially when there are spaces or special characters in your path.

For example, suppose an absolute path (Mac OS) is `/Users/Project Name With Spaces/src/main/resources/assets/style/style.css`, `toFile` news a `File` object from the absolute path string, `toURL` formats the given File object to a `URL` object, written as `file:/Users/Project%20Name%20With%20Spaces/src/main/resources/assets/style/style.css` (**NOTE** the prefix `file:` and how ` ` will be converted.). Then you can use `toString`, which should work fine then.
