### ISSUE TITLE
Return VS Save in Setting pane

### ISSUE THREAD

**Issue by zcmiyano** [CastleLab/COMP3021-2020Fall-PA2-Student-Version#25]
In the grading scheme 11 "Click "Settings/About" button, the changed default settings is displayed" Does it mean Save button was clicked before ( However test 10 is clicking return button) In the demo, by clicking return button, changes in players will be saved. Is this a bug?

**Comment by ArabelaTso** [comment]
If return by clicking the "Save" button, the changed default value should be saved (including changes in players), if return by clicking the "Return" button, the default value should NOT be saved. The specification isn't the order of things occurs, so rule 11 does NOT necessarily describe the result after the execution of rule 10.

It is the bug in the obfuscated demo, for the requirement of functionalities, please **refer to the grading specification** instead of the demo program, since the obfuscated version is for demo only.
