### ISSUE TITLE
SettingPane save and return button

### ISSUE THREAD

**Issue by DoVaKeitH** [CastleLab/COMP3021-2020Fall-PA2-Student-Version#4]
For the SettingPane, is it once you have clicked the save button, if you try to modify the field value and click "return" button, 
the field value modified will still being changed? 

so the save button is kind of flag whether once you have clicked it, every field value modified will always be saved no matter you click save or return

**Comment by ArabelaTso** [comment]
Sorry I cannot get your point. Once the "save" button is clicked, the values in all fields should be changed and saved and returned to main menu. When clicking "return" without "save", then the value should not be saved.

**Comment by DoVaKeitH** [comment]
But in the obfuscated version, when you have clicked save once, when you modified value in SettingPane again, no matter you click save or return, the value will be saved. So maybe it is a bug

**Comment by ArabelaTso** [comment]
Basically, when "save" button has been clicked in SettingPane, it will lead you to the main menu immediately, so you can only modify values by entering SettingPane again. The second time entering the SettingPane, whether the values are saved is still determined by whether "save" button has been clicked.

For example, steps as follow:

Example 1 Click Save button

  *   Click Setting / About (Result: show SettingPane) ->
  *   Edit Board size from 9 to 15 (Result: numberTextFiled has been changed from 9 to 15) ->
  *   Click Save button (Result: show MainMenuPane)->
  *   Click Setting / About (Result: show SettingPane with board size 15)

Example 2 Click Return button

  *   Click Setting / About (Result: show SettingPane) ->
  *   Edit Board size from 9 to 15 (Result: numberTextFiled has been changed from 9 to 15) ->
  *   Click Return button (Result: show MainMenuPane)->
  *   Click Setting / About (Result: show SettingPane with board size 9, instead of 15)

Hope this may clarify the logic, and please let me know if I understand you right. If not, could you please give an example of the bug you report?

I tried to click Return instead of Save after saving once, the logic works fine, so I assumed this is not the situation you described 🙁


Jialun



________________________________
发件人: DoVaKeitH <notifications@github.com>
发送时间: 2020年10月18日 21:28
收件人: CastleLab/COMP3021-2020Fall-PA2-Student-Version <COMP3021-2020Fall-PA2-Student-Version@noreply.github.com>
抄送: ArabelaTso <arabela_tso@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [CastleLab/COMP3021-2020Fall-PA2-Student-Version] SettingPane save and return button (#4)


But in the obfuscated version, when you have clicked save once, when you modified value in SettingPane again, no matter you click save or return, the value will be saved. So maybe it is a bug
