### ISSUE TITLE
About SoundFx in SettingPane

### ISSUE THREAD

**Issue by ccCLCcc** [CastleLab/COMP3021-2020Fall-PA2-Student-Version#41]
I am sorry to ask a question about  SettingPane again, but I really confused.

For the SoundFx button, do I need to press "Save" to save the state of SoundFx? Or the state of SoundFx is saved no matter I click "Save" or  "Return"? ("Save" button is only for the globalConfiguration and duration, excludes SoundFx?)

At #36, the answer is No, but at #5 (the last two comments), the answer is Yes... So which should I follow...

**Comment by ccCLCcc** [comment]
Also, for the Smart Random Player, what does "Random Player vs Smart Random player" mean? Does it mean one is player with random moves and one is player with smarter moves?
Or I just need to use "Player1: Computer" and "Player2: Computer" to play and export the .txt?

**Comment by ArabelaTso** [comment]
> At #36, the answer is No, but at #5 (the last two comments), the answer is Yes... So which should I follow...

 #36 is about "Use Default" at GamePane, not SettingPane.
At #5  the answer is NO (The answer is `They should only be saved when the "Save" button is clicked.`)

> Does it mean one is player with random moves and one is player with smarter moves?

Yes.

> I just need to use "Player1: Computer" and "Player2: Computer" to play and export the .txt?

Since Random Computer player and Smart Random player adopt different strategies (i.e., random and smart) to select the next move, so you need to make these two players adopt different strategies.

**Comment by ccCLCcc** [comment]
> Since Random Computer player and Smart Random player adopt different strategies (i.e., random and smart) to select the next move, so you need to make these two players adopt different strategies.

Does it mean that i should make a new Player class that is similar to the Random Player, for the Smart Player? Or I can add a button on the GamePane for a user to choose whether to use the Smart Player? Or is there any other way to do so... 
because I just add the implementation under the TODO of RandomPlayer...

**Comment by ArabelaTso** [comment]
> Does it mean that I should make a new Player class that is similar to the Random Player, for the Smart Player?

The class for `SmartRandomPlayer` is already provided:
https://github.com/CastleLab/COMP3021-2020Fall-PA2-Student-Version/blob/main/src/main/java/castle/comp3021/assignment/player/SmartRandomPlayer.java

> Or I can add a button on the GamePane for a user to choose whether to use the Smart Player? Or is there any other way to do so... because I just add the implementation under the TODO of RandomPlayer

You can implement it **either way** you like, since it is a bonus, there is no compulsory way how you implement it. At least you need to implement a way to enable "Smart vs Random" mode.

**Comment by ccCLCcc** [comment]
Thank you so much! I was using the old version of the skeleton code.. Thanks again!
